// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhVeAxLkd06gdmIKvQbOx8MFYHXycvCb4',
    appId: '1:1062489322739:web:3fb499bbc0a56e13523386',
    messagingSenderId: '1062489322739',
    projectId: 'wevent-e0d18',
    authDomain: 'wevent-e0d18.firebaseapp.com',
    storageBucket: 'wevent-e0d18.firebasestorage.app',
    measurementId: 'G-WGYKV96975',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGaQRaqpEHJsGqi9iOOkdj9qreoCnBIlw',
    appId: '1:1062489322739:android:1148e5ead99cc241523386',
    messagingSenderId: '1062489322739',
    projectId: 'wevent-e0d18',
    storageBucket: 'wevent-e0d18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOWJxCR8xuEmDPThjhWdYVjBq0tPP35x0',
    appId: '1:1062489322739:ios:a1829c41bf584408523386',
    messagingSenderId: '1062489322739',
    projectId: 'wevent-e0d18',
    storageBucket: 'wevent-e0d18.firebasestorage.app',
    iosBundleId: 'com.example.wevent3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOWJxCR8xuEmDPThjhWdYVjBq0tPP35x0',
    appId: '1:1062489322739:ios:a1829c41bf584408523386',
    messagingSenderId: '1062489322739',
    projectId: 'wevent-e0d18',
    storageBucket: 'wevent-e0d18.firebasestorage.app',
    iosBundleId: 'com.example.wevent3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhVeAxLkd06gdmIKvQbOx8MFYHXycvCb4',
    appId: '1:1062489322739:web:ba2e8ebd7f8f6ef8523386',
    messagingSenderId: '1062489322739',
    projectId: 'wevent-e0d18',
    authDomain: 'wevent-e0d18.firebaseapp.com',
    storageBucket: 'wevent-e0d18.firebasestorage.app',
    measurementId: 'G-YCTCFM2NQB',
  );
}
